# create github action to init and plan terrafrom
name: Terraform CD
on:
  push:
    branches:
      - master
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # get azure credentials from secrets
      - uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

      - name: Terraform Init
        run: |
          make init

      - name: Terraform Plan
        run: |
          make plan    
        env:
          ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TENANT_ID }}

      # - name: Terraform Apply
      #   uses: hashicorp/terraform-github-actions@master
      #   with:
      #     tf_actions_version: 0.12.24
      #     tf_actions_subcommand: 'apply'
      #     tf_actions_working_dir: 'terraform'
      #     tf_actions_comment: true
      #     tf_actions_add_comment: true
      #     tf_actions_comment: true
      #     tf_actions_working_dir: 'terraform'
      #     tf_actions_github_token: ${{ secrets.GITHUB_TOKEN }}
      #     tf_actions_run_tf_init: false

