# create github action to init and plan terrafrom
name: Terraform CD
on:
  push:
    branches:
      - master
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # get azure credentials from secrets
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Terraform Init
        run: |
          make init

      - name: Terraform Plan
        run: |
          make plan
      # - name: Terraform Apply
      #   uses: hashicorp/terraform-github-actions@master
      #   with:
      #     tf_actions_version: 0.12.24
      #     tf_actions_subcommand: 'apply'
      #     tf_actions_working_dir: 'terraform'
      #     tf_actions_comment: true
      #     tf_actions_add_comment: true
      #     tf_actions_comment: true
      #     tf_actions_working_dir: 'terraform'
      #     tf_actions_github_token: ${{ secrets.GITHUB_TOKEN }}
      #     tf_actions_run_tf_init: false

